/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}', './pages/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}', './store/**/*.ts', './hooks/**/*.ts', './services/**/*.ts', './constants/**/*.ts'],
  theme: {
    extend: {
      /* MOxE mobile-matching design tokens; theme-aware via CSS variables */
      colors: {
        moxe: {
          background: 'var(--moxe-bg)',
          surface: 'var(--moxe-surface)',
          text: 'var(--moxe-text)',
          textSecondary: 'var(--moxe-text-secondary)',
          border: 'var(--moxe-border)',
          primary: '#0095f6',
          accent: '#e1306c',
          success: '#00c853',
          danger: '#ff5252',
          warning: '#ffab00',
          storyRing: '#f09433',
          storyRing2: '#e1306c',
          storyRing3: '#833ab4',
          storyRing4: '#405de6',
        },
        ig: {
          gradientStart: '#F58529',
          gradientMid: '#DD2A7B',
          gradientEnd: '#8134AF',
          blue: '#0095F6',
          background: '#FAFAFA',
          darkBg: '#121212',
          card: '#FFFFFF',
          separator: '#DBDBDB',
          text: '#262626',
          textSecondary: '#8E8E8E',
          storyRing: '#C13584',
        },
        moxeAccent: {
          personal: '#262626',
          business: '#00A86B',
          creator: '#FFB800',
          job: '#8A2BE2',
        },
        /* MOxE Job Tools design-bible palette (ported from HTML UI.html/job-ui.html) */
        surface: '#0b1326',
        'on-tertiary': '#003824',
        primary: '#ffb3ad',
        'on-error-container': '#ffdad6',
        'tertiary-fixed-dim': '#4edea3',
        'error-container': '#93000a',
        'tertiary-fixed': '#6ffbbe',
        'secondary-container': '#ee9800',
        'primary-container': '#390003',
        'on-secondary-container': '#5b3800',
        'secondary-fixed-dim': '#ffb95f',
        'on-error': '#690005',
        'inverse-surface': '#dae2fd',
        'surface-container-highest': '#2d3449',
        'on-tertiary-container': '#009365',
        'on-primary-fixed-variant': '#930013',
        'outline-variant': '#45464d',
        'surface-bright': '#31394d',
        'surface-tint': '#ffb3ad',
        'on-secondary-fixed': '#2a1700',
        error: '#ffb4ab',
        'on-surface': '#dae2fd',
        'secondary-fixed': '#ffddb8',
        'on-primary-container': '#eb4142',
        secondary: '#ffb95f',
        'on-surface-variant': '#c6c6cd',
        'inverse-primary': '#b91a24',
        'surface-container': '#171f33',
        'surface-container-low': '#131b2e',
        'surface-container-high': '#222a3d',
        outline: '#909097',
        'surface-dim': '#0b1326',
        'primary-fixed': '#ffdad7',
        'on-primary': '#68000a',
        'surface-variant': '#2d3449',
        background: '#0b1326',
        'on-background': '#dae2fd',
        'surface-container-lowest': '#060e20',
        'tertiary-container': '#001c10',
        tertiary: '#4edea3',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        'on-primary-fixed': '#410004',
        'primary-fixed-dim': '#ffb3ad',
        'inverse-on-surface': '#283044',
        'secondary-fixed-dim': '#ffb95f',
        'on-secondary': '#472a00',
      },
      spacing: {
        'moxe-xs': '4px',
        'moxe-sm': '8px',
        'moxe-md': '16px',
        'moxe-lg': '24px',
        'moxe-xl': '32px',
      },
      borderRadius: {
        'moxe-sm': '4px',
        'moxe-md': '8px',
        'moxe-lg': '16px',
        /* design-bible job tools (also used by some copied markup) */
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        sans: ['system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        /* Used by some design-bible markup */
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'moxe-caption': ['12px', { lineHeight: '1.4' }],
        'moxe-body': ['14px', { lineHeight: '1.5' }],
        'moxe-body-lg': ['16px', { lineHeight: '1.5' }],
        'moxe-title': ['18px', { lineHeight: '1.3', fontWeight: '600' }],
        'moxe-title-lg': ['20px', { lineHeight: '1.3', fontWeight: '600' }],
        'moxe-headline': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'ig-caption': ['12px', { lineHeight: '1.4' }],
        'ig-body': ['14px', { lineHeight: '1.5' }],
        'ig-body-lg': ['16px', { lineHeight: '1.5' }],
        'ig-title3': ['20px', { lineHeight: '1.3', fontWeight: '600' }],
        'ig-title2': ['22px', { lineHeight: '1.3', fontWeight: '600' }],
        'ig-title1': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
      },
      backgroundImage: {
        'ig-gradient': 'linear-gradient(90deg, #F58529 0%, #DD2A7B 50%, #8134AF 100%)',
        'ig-gradient-vertical': 'linear-gradient(180deg, #F58529 0%, #DD2A7B 50%, #8134AF 100%)',
        'moxe-story': 'linear-gradient(135deg, #f09433 0%, #e1306c 50%, #833ab4 100%)',
      },
      maxWidth: {
        'ig-content': '470px',
        'moxe-shell': '428px',
      },
    },
  },
  plugins: [],
};
