import React, { useEffect, useRef, useState } from 'react';

const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:5007/api';

type AIMsgRole = 'user' | 'assistant' | 'system';

type AIMessage = {
  id: string;
  role: AIMsgRole;
  content: string;
  createdAt: string;
};

type AIChatResponse = {
  message: {
    id: string;
    role: 'assistant';
    content: string;
    createdAt: string;
  };
};

function useAuthHeaders() {
  const token = typeof window !== 'undefined' ? localStorage.getItem('token') : null;
  return token
    ? {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      }
    : { 'Content-Type': 'application/json' };
}

export default function Ai() {
  const [messages, setMessages] = useState<AIMessage[]>([]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [model, setModel] = useState<string>('gpt-4');

  const headers = useAuthHeaders();
  const bottomRef = useRef<HTMLDivElement | null>(null);

  const scrollToBottom = () => {
    if (bottomRef.current) {
      bottomRef.current.scrollIntoView({ behavior: 'smooth', block: 'end' });
    }
  };

  const loadHistory = async () => {
    setError(null);
    try {
      const res = await fetch(`${API_BASE}/job/ai/history?limit=50`, { headers });
      if (!res.ok) throw new Error('Failed to load AI history');
      const data = (await res.json()) as AIMessage[];
      // history is returned newest first; show in chronological order
      const ordered = [...(data || [])].sort(
        (a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime(),
      );
      setMessages(ordered);
      setTimeout(scrollToBottom, 50);
    } catch (e: any) {
      setError(e.message || 'Failed to load AI history');
    }
  };

  const send = async (e: React.FormEvent) => {
    e.preventDefault();
    const trimmed = input.trim();
    if (!trimmed) return;
    setError(null);

    const tempUserMessage: AIMessage = {
      id: `local-${Date.now()}`,
      role: 'user',
      content: trimmed,
      createdAt: new Date().toISOString(),
    };
    setMessages((prev) => [...prev, tempUserMessage]);
    setInput('');
    setLoading(true);
    setTimeout(scrollToBottom, 50);

    try {
      const res = await fetch(`${API_BASE}/job/ai/chat`, {
        method: 'POST',
        headers,
        body: JSON.stringify({
          prompt: trimmed,
          model,
          metadata: { source: 'job-ai-ui' },
        }),
      });
      if (!res.ok) {
        const text = await res.text();
        throw new Error(text || 'AI request failed');
      }
      const data = (await res.json()) as AIChatResponse;
      const assistantMsg: AIMessage = {
        id: data.message.id,
        role: 'assistant',
        content: data.message.content,
        createdAt: data.message.createdAt,
      };
      setMessages((prev) => [...prev, assistantMsg]);
      setTimeout(scrollToBottom, 50);
    } catch (e: any) {
      setError(e.message || 'AI request failed');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadHistory();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const renderMessage = (m: AIMessage) => {
    const isUser = m.role === 'user';
    const isAssistant = m.role === 'assistant';
    return (
      <div
        key={m.id}
        className={`flex ${isUser ? 'justify-end' : 'justify-start'} mb-2`}
      >
        <div
          className={`max-w-[80%] rounded-2xl px-3 py-2 text-sm whitespace-pre-wrap ${
            isUser
              ? 'bg-indigo-600 text-white rounded-br-sm'
              : isAssistant
              ? 'bg-slate-100 dark:bg-slate-800 text-slate-900 dark:text-slate-100 rounded-bl-sm'
              : 'bg-slate-50 dark:bg-slate-900 text-slate-800 dark:text-slate-100'
          }`}
        >
          {!isUser && (
            <div className="text-[11px] font-medium mb-0.5 text-slate-500 dark:text-slate-400">
              {isAssistant ? 'MOxE AI' : 'System'}
            </div>
          )}
          <div className="text-[13px] leading-snug">{m.content}</div>
          <div className="mt-1 text-[10px] text-slate-400">
            {new Date(m.createdAt).toLocaleTimeString([], {
              hour: '2-digit',
              minute: '2-digit',
            })}
          </div>
        </div>
      </div>
    );
  };

  return (
    <div className="flex flex-col lg:flex-row gap-6">
      <div className="w-full lg:w-72 space-y-4">
        <div>
          <h2 className="text-2xl font-semibold text-slate-800 dark:text-white mb-1">
            MOxE AI (Job)
          </h2>
          <p className="text-slate-600 dark:text-slate-400 text-sm">
            Ask MOxE AI for help with your Job workspace. Today this is a
            structured assistant stub; when a live model is wired, responses
            will be generated by the configured AI provider.
          </p>
        </div>

        {error && (
          <div className="p-3 rounded-lg bg-red-50 dark:bg-red-900/30 text-red-700 dark:text-red-200 text-xs">
            {error}
          </div>
        )}

        <div className="space-y-2">
          <label className="text-xs font-medium text-slate-700 dark:text-slate-200">
            Model
          </label>
          <select
            className="w-full rounded-md border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 px-3 py-1.5 text-sm text-slate-900 dark:text-slate-100"
            value={model}
            onChange={(e) => setModel(e.target.value)}
          >
            <option value="gpt-4">GPT‑4 (default)</option>
            <option value="claude-3">Claude 3</option>
            <option value="local">Local / internal</option>
          </select>
          <p className="text-[11px] text-slate-500 dark:text-slate-400">
            This is metadata only right now. When a real AI backend is
            configured, it can select the appropriate provider/model here.
          </p>
        </div>

        <button
          type="button"
          onClick={loadHistory}
          className="inline-flex items-center justify-center rounded-md border border-slate-300 dark:border-slate-700 px-3 py-1.5 text-xs font-medium text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-800"
        >
          Refresh history
        </button>
      </div>

      <div className="flex-1 min-w-0 flex flex-col rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 overflow-hidden">
        <div className="flex-1 min-h-[260px] max-h-[520px] overflow-y-auto px-4 py-3">
          {messages.length === 0 && (
            <div className="text-sm text-slate-500 dark:text-slate-400">
              Start a conversation with MOxE AI about your Job projects, code,
              or workflows. History is stored per Job account.
            </div>
          )}
          {messages.map((m) => renderMessage(m))}
          <div ref={bottomRef} />
        </div>

        <form
          onSubmit={send}
          className="border-t border-slate-200 dark:border-slate-800 px-3 py-2 flex items-end gap-2 bg-slate-50 dark:bg-slate-950/80"
        >
          <textarea
            className="flex-1 resize-none rounded-md border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 px-3 py-2 text-sm text-slate-900 dark:text-slate-100 max-h-32"
            placeholder="Ask MOxE AI a question about your Job account, projects, or code…"
            rows={2}
            value={input}
            onChange={(e) => setInput(e.target.value)}
          />
          <button
            type="submit"
            disabled={loading || !input.trim()}
            className="inline-flex items-center justify-center rounded-md bg-indigo-600 hover:bg-indigo-700 disabled:bg-indigo-400 text-white text-sm font-medium px-3 py-2"
          >
            {loading ? 'Thinking…' : 'Send'}
          </button>
        </form>
      </div>
    </div>
  );
}

